project_id = "xaozmulvcdealaemnebz"

[functions.generate-content]
verify_jwt = true

[functions.report-word-count]
verify_jwt = true

[functions.admin-stats]
verify_jwt = true

[functions.mock-subscribe]
verify_jwt = true
