import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Plus, Trash2, GripVertical, ChevronUp, ChevronDown } from "lucide-react";

export interface FormField {
  id: string;
  label: string;
  labelBn?: string;
  type: "text" | "textarea" | "select" | "number" | "toggle";
  placeholder?: string;
  placeholderBn?: string;
  required?: boolean;
  options?: { value: string; label: string; labelBn?: string }[];
  defaultValue?: string | number | boolean;
  maxLength?: number;
  minLength?: number;
  helpText?: string;
  helpTextBn?: string;
}

interface VisualFormBuilderProps {
  fields: FormField[];
  onChange: (fields: FormField[]) => void;
  showPreview?: boolean;
}

const FIELD_TYPES = [
  { value: "text", label: "Text Input" },
  { value: "textarea", label: "Textarea" },
  { value: "select", label: "Select Dropdown" },
  { value: "number", label: "Number" },
  { value: "toggle", label: "Toggle (Yes/No)" },
];

function generateFieldId(label: string, existingFields: FormField[]): string {
  const baseId = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    || "field";
  
  let id = baseId;
  let counter = 1;
  while (existingFields.some(f => f.id === id)) {
    id = `${baseId}_${counter}`;
    counter++;
  }
  return id;
}

function FieldRow({
  field,
  index,
  totalFields,
  onUpdate,
  onDelete,
  onMoveUp,
  onMoveDown,
}: {
  field: FormField;
  index: number;
  totalFields: number;
  onUpdate: (field: FormField) => void;
  onDelete: () => void;
  onMoveUp: () => void;
  onMoveDown: () => void;
}) {
  const [isExpanded, setIsExpanded] = useState(false);

  const handleLabelChange = (label: string, allFields: FormField[], currentId: string) => {
    // Auto-generate ID from label if ID matches previous auto-generated pattern
    const wasAutoGenerated = field.id === generateFieldId(field.label, allFields.filter(f => f.id !== currentId));
    const newId = wasAutoGenerated ? generateFieldId(label, allFields.filter(f => f.id !== currentId)) : field.id;
    onUpdate({ ...field, label, id: newId });
  };

  return (
    <Card className="border-l-4 border-l-primary/50">
      <CardContent className="p-4 space-y-4">
        {/* Main row - always visible */}
        <div className="flex items-start gap-3">
          <div className="flex flex-col gap-1 pt-2">
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              onClick={onMoveUp}
              disabled={index === 0}
            >
              <ChevronUp className="h-4 w-4" />
            </Button>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="h-6 w-6"
              onClick={onMoveDown}
              disabled={index === totalFields - 1}
            >
              <ChevronDown className="h-4 w-4" />
            </Button>
          </div>

          <div className="flex-1 grid grid-cols-1 md:grid-cols-4 gap-3">
            {/* Label */}
            <div>
              <Label className="text-xs text-muted-foreground">Label *</Label>
              <Input
                value={field.label}
                onChange={(e) => onUpdate({ ...field, label: e.target.value })}
                placeholder="e.g., Blog Title"
                className="h-9"
              />
            </div>

            {/* Type */}
            <div>
              <Label className="text-xs text-muted-foreground">Type</Label>
              <Select
                value={field.type}
                onValueChange={(v) => onUpdate({ 
                  ...field, 
                  type: v as FormField["type"],
                  options: v === "select" && !field.options?.length ? [{ value: "option1", label: "Option 1" }] : field.options
                })}
              >
                <SelectTrigger className="h-9">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {FIELD_TYPES.map((t) => (
                    <SelectItem key={t.value} value={t.value}>
                      {t.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Placeholder */}
            <div>
              <Label className="text-xs text-muted-foreground">Placeholder</Label>
              <Input
                value={field.placeholder || ""}
                onChange={(e) => onUpdate({ ...field, placeholder: e.target.value })}
                placeholder="Enter placeholder..."
                className="h-9"
              />
            </div>

            {/* Required toggle */}
            <div className="flex items-end gap-4">
              <div className="flex items-center gap-2">
                <Switch
                  checked={field.required || false}
                  onCheckedChange={(checked) => onUpdate({ ...field, required: checked })}
                />
                <Label className="text-xs">Required</Label>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="h-9 w-9 text-muted-foreground hover:text-foreground"
                onClick={() => setIsExpanded(!isExpanded)}
              >
                <span className="text-xs font-medium">{isExpanded ? "−" : "+"}</span>
              </Button>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="h-9 w-9 text-destructive hover:text-destructive hover:bg-destructive/10"
                onClick={onDelete}
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        {/* Select options - visible when type is select */}
        {field.type === "select" && (
          <div className="ml-12 pt-2 border-t">
            <Label className="text-xs text-muted-foreground mb-2 block">
              Options (comma-separated values)
            </Label>
            <Input
              value={field.options?.map(o => o.label).join(", ") || ""}
              onChange={(e) => {
                const values = e.target.value.split(",").map(v => v.trim()).filter(Boolean);
                onUpdate({
                  ...field,
                  options: values.map(v => ({
                    value: v.toLowerCase().replace(/[^a-z0-9]+/g, "_"),
                    label: v,
                  })),
                });
              }}
              placeholder="e.g., Professional, Casual, Funny"
              className="h-9"
            />
          </div>
        )}

        {/* Expanded options */}
        {isExpanded && (
          <div className="ml-12 pt-3 border-t space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs text-muted-foreground">Field ID (auto-generated)</Label>
                <Input
                  value={field.id}
                  onChange={(e) => onUpdate({ ...field, id: e.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "") })}
                  placeholder="field_id"
                  className="h-9 font-mono text-sm"
                />
              </div>
              <div>
                <Label className="text-xs text-muted-foreground">Help Text</Label>
                <Input
                  value={field.helpText || ""}
                  onChange={(e) => onUpdate({ ...field, helpText: e.target.value })}
                  placeholder="Describe what this field is for..."
                  className="h-9"
                />
              </div>
            </div>
            
            {(field.type === "text" || field.type === "textarea") && (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs text-muted-foreground">Min Length</Label>
                  <Input
                    type="number"
                    value={field.minLength || ""}
                    onChange={(e) => onUpdate({ ...field, minLength: e.target.value ? parseInt(e.target.value) : undefined })}
                    placeholder="0"
                    className="h-9"
                  />
                </div>
                <div>
                  <Label className="text-xs text-muted-foreground">Max Length</Label>
                  <Input
                    type="number"
                    value={field.maxLength || ""}
                    onChange={(e) => onUpdate({ ...field, maxLength: e.target.value ? parseInt(e.target.value) : undefined })}
                    placeholder="∞"
                    className="h-9"
                  />
                </div>
              </div>
            )}

            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs text-muted-foreground">Label (Bangla)</Label>
                <Input
                  value={field.labelBn || ""}
                  onChange={(e) => onUpdate({ ...field, labelBn: e.target.value })}
                  placeholder="বাংলা লেবেল"
                  className="h-9"
                />
              </div>
              <div>
                <Label className="text-xs text-muted-foreground">Placeholder (Bangla)</Label>
                <Input
                  value={field.placeholderBn || ""}
                  onChange={(e) => onUpdate({ ...field, placeholderBn: e.target.value })}
                  placeholder="বাংলা প্লেসহোল্ডার"
                  className="h-9"
                />
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function FormPreview({ fields }: { fields: FormField[] }) {
  if (fields.length === 0) {
    return (
      <div className="text-center text-muted-foreground py-8 border-2 border-dashed rounded-lg">
        <p>Add fields to see preview</p>
      </div>
    );
  }

  return (
    <div className="space-y-4 p-4 border rounded-lg bg-muted/30">
      <div className="flex items-center gap-2 mb-2">
        <Badge variant="outline" className="text-xs">Live Preview</Badge>
      </div>
      {fields.map((field) => (
        <div key={field.id} className="space-y-1.5">
          <Label className="text-sm">
            {field.label}
            {field.required && <span className="text-destructive ml-1">*</span>}
          </Label>
          
          {field.type === "text" && (
            <Input
              placeholder={field.placeholder}
              disabled
              className="bg-background"
            />
          )}
          
          {field.type === "textarea" && (
            <Textarea
              placeholder={field.placeholder}
              disabled
              className="bg-background"
              rows={3}
            />
          )}
          
          {field.type === "number" && (
            <Input
              type="number"
              placeholder={field.placeholder}
              disabled
              className="bg-background"
            />
          )}
          
          {field.type === "select" && (
            <Select disabled>
              <SelectTrigger className="bg-background">
                <SelectValue placeholder={field.placeholder || "Select..."} />
              </SelectTrigger>
              <SelectContent>
                {field.options?.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
          
          {field.type === "toggle" && (
            <div className="flex items-center gap-2">
              <Switch disabled />
              <span className="text-sm text-muted-foreground">
                {field.placeholder || "Yes / No"}
              </span>
            </div>
          )}
          
          {field.helpText && (
            <p className="text-xs text-muted-foreground">{field.helpText}</p>
          )}
        </div>
      ))}
    </div>
  );
}

export function VisualFormBuilder({ fields, onChange, showPreview = true }: VisualFormBuilderProps) {
  const handleAddField = () => {
    const newField: FormField = {
      id: generateFieldId("new_field", fields),
      label: "",
      type: "text",
      required: false,
    };
    onChange([...fields, newField]);
  };

  const handleUpdateField = (index: number, updatedField: FormField) => {
    const newFields = [...fields];
    newFields[index] = updatedField;
    onChange(newFields);
  };

  const handleDeleteField = (index: number) => {
    onChange(fields.filter((_, i) => i !== index));
  };

  const handleMoveUp = (index: number) => {
    if (index === 0) return;
    const newFields = [...fields];
    [newFields[index - 1], newFields[index]] = [newFields[index], newFields[index - 1]];
    onChange(newFields);
  };

  const handleMoveDown = (index: number) => {
    if (index === fields.length - 1) return;
    const newFields = [...fields];
    [newFields[index], newFields[index + 1]] = [newFields[index + 1], newFields[index]];
    onChange(newFields);
  };

  return (
    <div className={showPreview ? "grid grid-cols-1 lg:grid-cols-2 gap-6" : ""}>
      {/* Builder */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <Label className="text-base font-medium">Form Fields</Label>
          <Badge variant="secondary" className="text-xs">
            {fields.length} field{fields.length !== 1 ? "s" : ""}
          </Badge>
        </div>
        
        {fields.length === 0 ? (
          <div className="text-center py-8 border-2 border-dashed rounded-lg">
            <p className="text-muted-foreground mb-3">No fields yet</p>
            <Button type="button" onClick={handleAddField} variant="outline" size="sm">
              <Plus className="h-4 w-4 mr-2" />
              Add First Field
            </Button>
          </div>
        ) : (
          <div className="space-y-3">
            {fields.map((field, index) => (
              <FieldRow
                key={`${field.id}-${index}`}
                field={field}
                index={index}
                totalFields={fields.length}
                onUpdate={(f) => handleUpdateField(index, f)}
                onDelete={() => handleDeleteField(index)}
                onMoveUp={() => handleMoveUp(index)}
                onMoveDown={() => handleMoveDown(index)}
              />
            ))}
            
            <Button
              type="button"
              onClick={handleAddField}
              variant="outline"
              className="w-full border-dashed"
            >
              <Plus className="h-4 w-4 mr-2" />
              Add Field
            </Button>
          </div>
        )}
      </div>

      {/* Preview */}
      {showPreview && (
        <div className="space-y-3">
          <Label className="text-base font-medium">Form Preview</Label>
          <FormPreview fields={fields} />
        </div>
      )}
    </div>
  );
}
